In [1]:
import pandas as pd
from pprint import pprint

In [29]:
price_info = pd.read_json('./stockinfoR.json')
test_df = pd.DataFrame(price_info)
test_df.dropna()
test_df.head(20)

,Ticker,name,sector,opening,closing,high,low
0,MMM,3M Company,Industrials,"[[2021-08-02, 199.07]]","[[2021-08-02, 197.52]]","[[2021-08-02, 200.7]]","[[2021-08-02, 197.435]]"
1,ABT,Abbott Laboratories,Health Care,"[[2021-08-02, 121.5]]","[[2021-08-02, 120.92]]","[[2021-08-02, 121.78]]","[[2021-08-02, 120.175]]"
2,ABBV,AbbVie Inc.,Health Care,"[[2021-08-02, 116.89]]","[[2021-08-02, 115.45]]","[[2021-08-02, 117.24]]","[[2021-08-02, 115.41]]"
3,ABMD,Abiomed,Health Care,"[[2021-08-02, 329.81]]","[[2021-08-02, 328.36]]","[[2021-08-02, 331.17]]","[[2021-08-02, 325.25]]"
4,ACN,Accenture,Information Technology,"[[2021-08-02, 319.27]]","[[2021-08-02, 316.08]]","[[2021-08-02, 319.49]]","[[2021-08-02, 315.5]]"
5,ATVI,Activision Blizzard,Communication Services,"[[2021-08-02, 84.03]]","[[2021-08-02, 82.76]]","[[2021-08-02, 84.165]]","[[2021-08-02, 82.54]]"
6,ADBE,Adobe Inc.,Information Technology,"[[2021-08-02, 625.87]]","[[2021-08-02, 618.75]]","[[2021-08-02, 627.6]]","[[2021-08-02, 612.93]]"
7,AMD,Advanced Micro Devices,Information Technology,"[[2021-08-02, 105.93]]","[[2021-08-02, 108.63]]","[[2021-08-02, 110.33]]","[[2021-08-02, 103.83]]"
8,AAP,Advance Auto Parts,Consumer Discretionary,"[[2021-08-02, 213.19]]","[[2021-08-02, 212.71]]","[[2021-08-02, 213.92]]","[[2021-08-02, 210.4]]"
9,AES,AES Corp,Utilities,"[[2021-08-02, 23.92]]","[[2021-08-02, 23.57]]","[[2021-08-02, 23.92]]","[[2021-08-02, 23.52]]"
10,AFL,Aflac,Financials,"[[2021-08-02, 55.31]]","[[2021-08-02, 54.71]]","[[2021-08-02, 56.11]]","[[2021-08-02, 54.64]]"
11,A,Agilent Technologies,Health Care,"[[2021-08-02, 154.05]]","[[2021-08-02, 153.07]]","[[2021-08-02, 154.3]]","[[2021-08-02, 152.52]]"
12,APD,Air Products & Chemicals,Materials,"[[2021-08-02, 292.37]]","[[2021-08-02, 288.73]]","[[2021-08-02, 293.66]]","[[2021-08-02, 288.32]]"
13,AKAM,Akamai Technologies,Information Technology,"[[2021-08-02, 119.86]]","[[2021-08-02, 118.9]]","[[2021-08-02, 120.0]]","[[2021-08-02, 117.23]]"
14,ALK,Alaska Air Group,Industrials,"[[2021-08-02, 58.21]]","[[2021-08-02, 56.71]]","[[2021-08-02, 59.73]]","[[2021-08-02, 56.62]]"
15,ALB,Albemarle Corporation,Materials,"[[2021-08-02, 208.36]]","[[2021-08-02, 206.9]]","[[2021-08-02, 208.96]]","[[2021-08-02, 204.63]]"
16,ARE,Alexandria Real Estate Equities,Real Estate,"[[2021-08-02, 202.09]]","[[2021-08-02, 203.01]]","[[2021-08-02, 203.59]]","[[2021-08-02, 201.84]]"
17,ALXN,Alexion Pharmaceuticals,Health Care,[],[],[],[]
18,ALGN,Align Technology,Health Care,"[[2021-08-02, 700.0]]","[[2021-08-02, 700.0]]","[[2021-08-02, 713.7]]","[[2021-08-02, 695.6]]"
19,ALLE,Allegion,Industrials,"[[2021-08-02, 137.05]]","[[2021-08-02, 135.87]]","[[2021-08-02, 138.57]]","[[2021-08-02, 135.7]]"

In [5]:
d = {'Ticker':[], 'date':[], 'sector':[],'name':[],'opening':[],'closing':[], 'high':[], 'low':[]}
Odf = pd.DataFrame(d)
Odf

Empty DataFrame
Columns: [Ticker, date, sector, name, opening, closing, high, low]
Index: []

In [25]:
pprint(price_info['opening'][18][0][1])

700.0

In [33]:
for i in range(0,502):
    try:
        print(i)
        opening = price_info['opening'][17][0][1] #pulls opening price list for the currently selected company
        close = price_info['closing'][i][0][1] #pulls closing price list for the currently selected company
        high = price_info['high'][i][0][1] #pulls high price list for the currently selected company
        low = price_info['low'][i][0][1] #pulls low price list for the currently selected company
        ticker = price_info['Ticker'][i]
        name = price_info['name'][i]
        sector = price_info['sector'][i]
        date = price_info['opening'][i][0][0]
        Odf = Odf.append({'Ticker': ticker,
                        'date': date,
                        'sector': sector,
                        'name': name,
                        'opening': opening,
                        'closing': close,}, ignore_index=True)
    except:
        pass

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501