In [1]:
import pandas as pd
from pprint import pprint

In [2]:
data = pd.read_csv('./total_us_stock_data400_days.csv')
total_df = pd.DataFrame(data)
total_df

        Ticker     opening     closing    NextHigh        high         low
0        BRK.A  343750.000  342270.060  344975.000  344642.340  340965.000
1        BRK.A  341850.000  343720.000  336162.660  344975.000  340600.000
2        BRK.A  335000.000  332800.000  335000.000  336162.660  330940.000
3        BRK.A  333195.060  328200.000  330602.750  335000.000  325900.000
4        BRK.A  328200.000  325115.000  322292.000  330602.750  324360.000
...        ...         ...         ...         ...         ...         ...
2380001  VTAQR       0.180       0.180       0.185       0.180       0.175
2380002  VTAQR       0.185       0.178       0.172       0.185       0.178
2380003  VTAQR       0.172       0.172       0.200       0.172       0.172
2380004  VTAQR       0.170       0.200       0.200       0.200       0.150
2380005  VTAQR       0.190       0.200       0.199       0.200       0.190

[2380006 rows x 6 columns]

In [3]:
data = pd.read_csv('../Machine_learning/Alpacca_NYSE_NASDAQ_List.csv')
tckr = data['Tckr'].tolist()
tckr

['AMRC',
 'AAT',
 'AAON',
 'AAP',
 'BNNRU',
 'AAPL',
 'AB',
 'AAQC',
 'AAQC.U',
 'ABC',
 'ABEV',
 'AAXJ',
 'ABGI',
 'ABBV',
 'ABSI',
 'ABEO',
 'ERJ',
 'GS',
 'ABOS',
 'ICUI',
 'ABST',
 'ABT',
 'ACCD',
 'ABTX',
 'ABVC',
 'ACA',
 'ACB',
 'ACBA',
 'ACEL',
 'ACGL',
 'ACH',
 'ACHL',
 'PDEX',
 'PGNY',
 'PLMIU',
 'NE',
 'PVG',
 'QAT',
 'RACE',
 'RGS',
 'ACII.U',
 'ACLS',
 'SR',
 'ACMR',
 'ACOR',
 'ACQR',
 'UNVR',
 'ACR',
 'ACRE',
 'SUN',
 'ACT',
 'ADEX',
 'ADIL',
 'ADOC',
 'ADS',
 'ADXN',
 'AEMD',
 'AES',
 'AFAQU',
 'AFGE',
 'AFINP',
 'AGAC',
 'AGCB',
 'AGFS',
 'AGM',
 'AGNCP',
 'AGR',
 'AGTC',
 'AHCO',
 'AIA',
 'AIHS',
 'AIRG',
 'AIV',
 'AJXA',
 'AKO.B',
 'AKUS',
 'ALB',
 'ALE',
 'ACTD',
 'ACWX',
 'ADEX.U',
 'ADM',
 'ADOCR',
 'ADSK',
 'ADXS',
 'AEFC',
 'AENZ',
 'AESC',
 'AFB',
 'AFI',
 'AFL',
 'AFT',
 'AGAC.U',
 'AGCO',
 'AGI',
 'AGM.A',
 'AGNG',
 'AGRI',
 'AGTI',
 'AHH',
 'AIC',
 'AINV',
 'AIZ',
 'AKAM',
 'AKR',
 'AKYA',
 'ALBO',
 'ALEC',
 'ALGN',
 'ALJJ',
 'ALLO',
 'ALPAU',
 'ALV',
 'AMBC',
 'AMD',
 'AMGN',
 'AMKR',
 'ACTG',
 'ADAG',
 'ADF',
 'ADTN',
 'AEG',
 'AEO',
 'AESE',
 'AFG',
 'AFIB',
 'AFTR.U',
 'AGBA',
 'AGCUU',
 'AGFY',
 'AGIL',
 'AGMH',
 'AGO',
 'AGRO',
 'AGX',
 'AHPAU',
 'AIKI',
 'AIO',
 'AIRR',
 'AIZN',
 'AKBA',
 'AKRO',
 'AL',
 'ALC',
 'ALEX',
 'ALGS',
 'ALK',
 'ALLT',
 'ALRM',
 'ALTO',
 'ALVR',
 'AME',
 'AMH',
 'AMOT',
 'ADAP',
 'ADMS',
 'ADP',
 'ADTX',
 'AEHAU',
 'AEP',
 'AEYE',
 'AFGB',
 'AGBAR',
 'AGD',
 'AGIO',
 'AGNCM',
 'AGRX',
 'AGYS',
 'AHPI',
 'AIF',
 'AIQ',
 'AIRT',
 'AJG',
 'AKIC',
 'AKTS',
 'ALAC',
 'ALCC',
 'ALF',
 'ALGT',
 'ALKS',
 'ALLY',
 'ALRN',
 'ALTR',
 'ALYA',
 'AMBP',
 'AMED',
 'AMHC',
 'AMN',
 'ACV',
 'ADBE',
 'ADGI',
 'ADN',
 'ADPT',
 'ADUS',
 'AEACU',
 'AEHR',
 'AER',
 'AEZS',
 'AFGC',
 'AFIN',
 'AFMD',
 'AFYA',
 'AGBAU',
 'AGGR',
 'AGL',
 'AGNCN',
 'AGS',
 'AHT',
 'AIG',
 'AIMC',
 'AIR',
 'AIRTP',
 'AJRD',
 'AKICU',
 'AKTX',
 'ALACR',
 'ALCO',
 'ALHC',
 'ALKT',
 'ALNA',
 'ALRS',
 'ALTU',
 'AM',
 'AMCIU',
 'AMEH',
 'AMHCU',
 'AMP',
 'ACWI',
 'ADER',
 'ADI',
 'ADNT',
 'ADX',
 'AEE',
 'AEI',
 'AERI',
 'AFAQ',
 'AFGD',
 'AFINO',
 'AFRM',
 'AG',
 'AGC',
 'AGEN',
 'AGGRU',
 'AGLE',
 'AGNCO',
 'AGZD',
 'AI',
 'AIH',
 'AIN',
 'AIRC',
 'AIT',
 'AJX',
 'AKO.A',
 'AKU',
 'ALACU',
 'ALDX',
 'ALG',
 'ALIM',
 'ALLE',
 'ALNY',
 'ALSN',
 'ALTUU',
 'AMAL',
 'AMCR',
 'AMNB',
 'ALGM',
 'ALIT',
 'ALLK',
 'ALOT',
 'ALT',
 'ALTY',
 'AMAM',
 'AMCX',
 'AMG',
 'AMK',
 'AMPG',
 'AMRK',
 'AMSF',
 'AMTI',
 'AMX',
 'ANAC.U',
 'ANF',
 'ANIK',
 'ANTE',
 'ANZUU',
 'APACU',
 'APG',
 'APLS',
 'APP',
 'APRN',
 'APTS',
 'AQB',
 'AQST',
 'ARCE',
 'ARD',
 'AREC',
 'ARI',
 'ARR',
 'ARTW',
 'ASA',
 'ASAXU',
 'ASGI',
 'ASLE',
 'AMOV',
 'AMPI.U',
 'AMRX',
 'AMT',
 'AMZN',
 'ANEB',
 'ANGL',
 'ANNX',
 'AOUT',
 'APDN',
 'APH',
 'APMIU',
 'APPN',
 'APSG.U',
 'APVO',
 'AQNA',
 'AR',
 'ARC',
 'ARCO',
 'ARDX',
 'ARGO',
 'ARKO',
 'ARLP',
 'AROW',
 'ARTA',
 'ARWR',
 'ASAQ',
 'ASMB',
 'ASPC',
 'ASR',
 'ASTR',
 'ASZ',
 'ATAQ.U',
 'ATEC',
 'ATHE',
 'ATLCP',
 'AMSC',
 'AMTBB',
 'AMWL',
 'ANAC',
 'ANGO',
 'ANSS',
 'ANZU',
 'AOMR',
 'APA',
 'APEN',
 'APLE',
 'APOP',
 'APRE',
 'APTO',
 'APYX',
 'AQNU',
 'ARAY',
 'ARCC',
 'ARGX',
 'ARKR',
 'ARQT',
 'ARTNA',
 'ARYE',
 'ASAX',
 'ASG',
 'ASND',
 'ASPN',
 'ASRV',
 'ASUR',
 'ATA',
 'ATC',
 'ATEX',
 'ATHN',
 'ATMR.U',
 'ATRA',
 'ATXS',
 'AUVI',
 'AMPH',
 'AMRN',
 'AMST',
 'AMYT',
 'ANAT',
 'ANIP',
 'AOS',
 'APAM',
 'APGB',
 'APLT',
 'APPF',
 'APTV',
 'AQMS',
 'AQUA',
 'ARBG',
 'ARCH',
 'ARDC',
 'ARES',
 'ARL',
 'ARNA',
 'ARRW',
 'ARVL',
 'ASAI',
 'ASB',
 'ASGN',
 'ASLN',
 'ASPA',
 'ASPU',
 'ASTC',
 'ATAI',
 'ATCOL',
 'ATGE',
 'ATIP',
 'ATRS',
 'AUBAP',
 'AMPI',
 'AMRS',
 'AMSWA',
 'AMTX',
 'ANDE',
 'ANGI',
 'ANIX',
 'ANTM',
 'AOD',
 'AOSL',
 'APD',
 'APGB.U',
 'APM',
 'APPH',
 'APSG',
 'APTX',
 'AQN',
 'AQWA',
 'ARBGU',
 'ARDS',
 'ARGD',
 'ARLO',
 'AROC',
 'ARRY',
 'ARW',
 'ASAN',
 'ASC',
 'ASH',
 'ASPAU',
 'ASTE',
 'ASYS',
 'ATAQ',
 'ATCX',
 'ATHA',
 'ATLC',
 'ATOM',
 'ATSPU',
 'AUDC',
 'AVAH',
 'AMR',
 'AMTB',
 'AMWD',
 'ANAB',
 'ANET',
 'ANGN',
 'ANPC',
 'ANY',
 'AP',
 'APEI',
 'API',
 'APO',
 'APPS',
 'APWC',
 'AQNB',
 'ARAV',
 'ARCB',
 'ARCT',
 'ARE',
 'ARMK',
 'ARQQ',
 'ARTL',
 'ARYD',
 'ASAQ.U',
 'ASET',
 'ASML',
 'ASPCU',
 'ASRT',
 'ASTS',
 'ASZ.U',
 'ATAX',
 'ATER',
 'ATHM',
 'ATMR',
 'ATR',
 'ATVCU',
 'ASO',
 'ASPS',
 'ASRVP',
 'ASX',
 'ATA.U',
 'ATCO',
 'ATIF',
 'ATNI',
 'ATRO',
 'AUB',
 'AURCU',
 'AUY',
 'AVB',
 'AVDL',
 'AVGOP',
 'AVK',
 'AVPT',
 'AVTX',
 'AWRE',
 'AXDX',
 'AXP',
 'AY',
 'AZEK',
 'AZUL',
 'BAC',
 'BAMH',
 'BANR',
 'BBDO',
 'BBIO',
 'BBVA',
 'BCAC',
 'BCE',
 'BCOW',
 'BCTX',
 'BDC',
 'ATOS',
 'ATVC',
 'AUID',
 'AUTL',
 'AVAL',
 'AVD',
 'AVID',
 'AVNT',
 'AVT',
 'AVXL',
 'AWK',
 'AXLA',
 'AXTA',
 'AYTU',
 'AZRE',
 'BA',
 'BAND',
 'BBCP',
 'BBI',
 'BBN',
 'BBSI',
 'BBY',
 'BCBP',
 'BCH',
 'BCRX',
 'BCYC',
 'BEAM',
 'BEN',
 'BGB',
 'BGSF',
 'BH',
 'BHFAL',
 'AUTO',
 'AVAN',
 'AVEO',
 'AVNW',
 'AVTE',
 'AVY',
 'AWP',
 'AX',
 'AXNX',
 'AXTI',
 'AYX',
 'BALY',
 'BANF',
 'BARK',
 'BAX',
 'BBD',
 'BBIG',
 'BBU',
 'BC',
 'BCC',
 'BCOR',
 'BCSF',
 'BCYP',
 'BDSI',
 'BECN',
 'BENE',
 'BEST',
 'BFI',
 'BGCP',
 'BGNE',
 'BGSX',
 'BH.A',
 'BHFAN',
 'BHP',
 'AUS.U',
 'AVA',
 'AVCO',
 'AVGR',
 'AVRO',
 'AWF',
 'AXGN',
 'AXR',
 'AYI',
 'AZN',
 'AZYO',
 'BAH',
 'BAMI',
 'BANX',
 'BBBY',
 'BBW',
 'BCACU',
 'BCEI',
 'BCML',
 'BCPC',
 'BDN',
 'BDX',
 'BEKE',
 'BEPH',
 'BFAM',
 'BFZ',
 'BGRY',
 'BGX',
 'BHE',
 'BHG',
 'BHSEU',
 'AVAN.U',
 'AVGO',
 'AVIR',
 'AVO',
 'AVTR',
 'AVYA',
 'AWR',
 'AXON',
 'AZRX',
 'BABA',
 'BAM',
 'BANFP',
 'BASE',
 'BBAR',
 'BBDC',
 'BBQ',
 'BCAB',
 'BCLI',
 'BCOV',
 'BCYPU',
 'BDJ',
 'BDSX',
 'BENER',
 'BF.A',
 'BFST',
 'BGFV',
 'BGR',
 'BGSX.U',
 'BHAT',
 'BHFAO',
 'BHR',
 'BHVN',
 'AVCT',
 'AVNS',
 'AWH',
 'AXL',
 'AXS',
 'AYLA',
 'AZO',
 'AZZ',
 'BAK',
 'BAMR',
 'BAOS',
 'BATRA',
 'BBGI',
 'BBL',
 'BBWI',
 'BCAT',
 'BCEL',
 'BCO',
 'BCX',
 'BE',
 'BELFB',
 'BERY',
 'BFC',
 'BG',
 'BGIO',
 'BGS',
 'BGY',
 'BHF',
 'BHK',
 'BHTG',
 'BICK',
 'BIGZ',
 'BDTX',
 'BEDU',
 'BEP',
 'BF.B',
 'BGH',
 'BGRN',
 'BGT',
 'BHFAP',
 'BHSE',
 'BIB',
 'BIGC',
 'BIOT',
 'BJK',
 'BKEPP',
 'BLCT',
 'BLE',
 'BLIN',
 'BLNGU',
 'BLTSU',
 'BLW',
 'BMTC',
 'BNDX',
 'BNS',
 'BOAC.U',
 'BOLT',
 'BOOT',
 'BOTJ',
 'BOXL',
 'BPOPN',
 'BHLB',
 'BB',
 'BIDU',
 'BIIB',
 'BIO.B',
 'BIP',
 'BITE',
 'BKE',
 'BKN',
 'BKSY',
 'BLBD',
 'BLFY',
 'BLL',
 'BLPH',
 'BLUE',
 'BMRA',
 'BND',
 'BNFT',
 'BNTX',
 'BOH',
 'BON',
 'BOSC',
 'BOWX',
 'BPMP',
 'BPTH',
 'BQ',
 'BREZ',
 'BRIV',
 'BRKS',
 'BRO',
 'BRSP',
 'BSAC',
 'BSCE',
 'BSCR',
 'BSET',
 'BSJL',
 'BSJS',
 'BHV',
 'BIF',
 'BIOC',
 'BIPC',
 'BITE.U',
 'BJ',
 'BKI',
 'BKNG',
 'BKT',
 'BLCM',
 'BLDP',
 'BLMN',
 'BLSA',
 'BMBL',
 'BMRC',
 'BNGO',
 'BNY',
 'BOWXU',
 'BPOP',
 'BPTS',
 'BR',
 'BREZR',
 'BRIVU',
 'BRLI',
 'BROG',
 'BRW',
 'BSAE',
 'BSCL',
 'BSCS',
 'BSGA',
 'BSJN',
 'BSL',
 'BIG',
 'BILI',
 'BIOL',
 'BIPH',
 'BITF',
 'BK',
 'BKEP',
 'BKR',
 'BLCN',
 'BLDR',
 'BLI',
 'BLND',
 'BLTS',
 'BME',
 'BMRN',
 'BNDW',
 'BNR',
 'BOAC',
 'BOCH',
 'BOKF',
 'BOOM',
 'BOX',
 'BPOPM',
 'BPYPM',
 'BRAG',
 'BRK.A',
 'BRLIR',
 'BROS',
 'BRX',
 'BSAQ',
 'BSCM',
 'BSCT',
 'BSGAR',
 'BSJO',
 'BSM',
 'BSMR',
 'BIMI',
 'BIOTU',
 'BIS',
 'BJRI',
 'BKCC',
 'BKSC',
 'BKYI',
 'BLD',
 'BLK',
 'BLNK',
 'BLU',
 'BLX',
 'BMEZ',
 'BNL',
 'BNSO',
 'BOAS',
 'BODY',
 'BOTZ',
 'BP',
 'BPRN',
 'BPYPO',
 'BRCN',
 'BRKL',
 'BRMK',
 'BRPMU',
 'BSBK',
 'BSCO',
 'BSDE',
 'BSGM',
 'BSJQ',
 'BSMM',
 'BIO',
 'BIOX',
 'BIT',
 'BIVI',
 'BKD',
 'BKH',
 'BL',
 'BLDE',
 'BLFS',
 'BLKB',
 'BLUA.U',
 'BMI',
 'BMY',
 'BNED',
 'BNTC',
 'BOAS.U',
 'BOE',
 'BOMN',
 'BORR',
 'BPMC',
 'BPT',
 'BPYPP',
 'BRDG',
 'BRID',
 'BRKR',
 'BRQS',
 'BSA',
 'BSBR',
 'BSCQ',
 'BSIG',
 'BSJR',
 'BSMN',
 'BSMU',
 'BST',
 'BPYPN',
 'BRBR',
 'BRFS',
 'BRK.B',
 'BRLIU',
 'BRP',
 'BRY',
 'BSAQ.U',
 'BSCN',
 'BSCU',
 'BSGAU',
 'BSJP',
 'BSML',
 'BSMS',
 'BSQR',
 'BTA',
 'BTCM',
 'BTNB',
 'BTWNU',
 'BUR',
 'BVH',
 'BWAC',
 'BWEN',
 'BWXT',
 'BXRX',
 'BYND',
 'CACG',
 'CAG',
 'CAKE',
 'CALM',
 'CAPR',
 'CARS',
 'CASH',
 'CATC',
 'CBAH.U',
 'CBNK',
 'CCAC.U',
 'BSMO',
 'BSMX',
 'BSVN',
 'BTAQU',
 'BTT',
 'BUI',
 'BVXV',
 'BWB',
 'BWMN',
 'BXC',
 'BYD',
 'BYTS',
 'CABA',
 'CADL',
 'CAHCU',
 'CALB',
 'CAMP',
 'CANO',
 'CARE',
 'CAS',
 'CASY',
 'CBD',
 'CBRE',
 'CBU',
 'CCB',
 'CCM',
 'CCV.U',
 'CDC',
 'CDLX',
 'CE',
 'CELU',
 'CENX',
 'CGAU',
 'BSMQ',
 'BSN.U',
 'BSX',
 'BTB',
 'BTI',
 'BTU',
 'BUD',
 'BW',
 'BWBBP',
 'BWMX',
 'BXMT',
 'BYFC',
 'BYTSU',
 'CABO',
 'CAE',
 'CAI',
 'CAMT',
 'CARG',
 'CAS.U',
 'CAT',
 'CB',
 'CBFV',
 'CC',
 'CCCC',
 'CCI',
 'CCMP',
 'CCRN',
 'CCVI',
 'CDE',
 'CDMO',
 'CDW',
 'CECE',
 'CEIX',
 'CERN',
 'CFG',
 'CGNT',
 'BSMT',
 'BSRR',
 'BTAI',
 'BTCY',
 'BTO',
 'BURL',
 'BVN',
 'BWACU',
 'BWFG',
 'BXS',
 'BYRN',
 'BZUN',
 'CACI',
 ...]

In [4]:
tradeablu_huge_df = total_df[total_df.Ticker.isin(tckr)]

In [28]:
tradeablu_huge_df['change']= (abs(tradeablu_huge_df['high'])/tradeablu_huge_df['low']*100)-100
tradeablu_huge_df

<ipython-input-28-a623f4c6f592>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tradeablu_huge_df['change']= (abs(tradeablu_huge_df['high'])/tradeablu_huge_df['low']*100)-100

,Ticker,opening,closing,NextHigh,high,low,change
0,BRK.A,343750.000,342270.060,344975.000,344642.340,340965.000,1.078510
1,BRK.A,341850.000,343720.000,336162.660,344975.000,340600.000,1.284498
2,BRK.A,335000.000,332800.000,335000.000,336162.660,330940.000,1.578129
3,BRK.A,333195.060,328200.000,330602.750,335000.000,325900.000,2.792268
4,BRK.A,328200.000,325115.000,322292.000,330602.750,324360.000,1.924636
...,...,...,...,...,...,...,...
2380001,VTAQR,0.180,0.180,0.185,0.180,0.175,2.857143
2380002,VTAQR,0.185,0.178,0.172,0.185,0.178,3.932584
2380003,VTAQR,0.172,0.172,0.200,0.172,0.172,0.000000
2380004,VTAQR,0.170,0.200,0.200,0.200,0.150,33.333333
2380005,VTAQR,0.190,0.200,0.199,0.200,0.190,5.263158

In [6]:
TckrDf = tradeablu_huge_df.groupby(tradeablu_huge_df['Ticker'])

In [7]:
changeList = TckrDf['change'].mean()
changeList

Ticker
A         2.287171
AA        5.945183
AAC       0.631770
AAC.U     0.757459
AACG     10.552098
           ...
ZWRKU     0.908163
ZY        8.936489
ZYME      5.960570
ZYNE      7.861464
ZYXI      7.032226
Name: change, Length: 7372, dtype: float64

In [54]:
Changedf = pd.DataFrame(changeList)
Changedf = Changedf.sort_values(by='change', ascending=False)
# gen5df = gen5df.drop([0, 50])
# gen5df = gen5df.head(500)
Changedf = Changedf.dropna()
Changedf = Changedf.reset_index(drop=False)
gen5df = Changedf.loc[4000:4500]
gen5df

     Ticker    change
4000   SRCE  3.638804
4001   FARO  3.637514
4002    HLT  3.637247
4003   KRNY  3.636946
4004   DSPG  3.636899
...     ...       ...
4496    SJW  3.114710
4497    BMI  3.114298
4498     DD  3.110141
4499    EMN  3.108378
4500    OMC  3.107314

[501 rows x 2 columns]

In [55]:
gen5df = gen5df.reset_index(drop=True)
gen5df

    Ticker    change
0     SRCE  3.638804
1     FARO  3.637514
2      HLT  3.637247
3     KRNY  3.636946
4     DSPG  3.636899
..     ...       ...
496    SJW  3.114710
497    BMI  3.114298
498     DD  3.110141
499    EMN  3.108378
500    OMC  3.107314

[501 rows x 2 columns]

In [56]:
gen5TckrList = gen5df['Ticker'].tolist()
gen5Tckr = {'Tckr': gen5TckrList}
gen5Tckr = pd.DataFrame(gen5Tckr)
gen5Tckr.to_csv(r'../Machine_Learning/G12List.csv', index = False)
gen5Tckr

     Tckr
0    SRCE
1    FARO
2     HLT
3    KRNY
4    DSPG
..    ...
496   SJW
497   BMI
498    DD
499   EMN
500   OMC

[501 rows x 1 columns]

In [39]:
G5trainingData = total_df[total_df.Ticker.isin(gen5TckrList)]
G5trainingData = G5trainingData.reset_index(drop=True)
G5trainingData.to_csv(r'../Machine_Learning/MLData12.csv', index = False)
G5trainingData

       Ticker   opening   closing  NextHigh      high       low
0        MNDY  173.1500  176.0200  194.9900  181.9999  155.0100
1        MNDY  179.7500  194.5900  218.9600  194.9900  176.5700
2        MNDY  193.0000  205.0400  217.7600  218.9600  189.9140
3        MNDY  210.9500  210.0000  214.9899  217.7600  198.0300
4        MNDY  214.3200  214.6600  219.8600  214.9899  205.0000
...       ...       ...       ...       ...       ...       ...
169290  SPKAR    0.3601    0.3600    0.3501    0.3601    0.3600
169291  SPKAR    0.3501    0.3401    0.3200    0.3501    0.3400
169292  SPKAR    0.3200    0.3200    0.3221    0.3200    0.3200
169293  SPKAR    0.3210    0.3221    0.3251    0.3221    0.3210
169294  SPKAR    0.3251    0.3251    0.3300    0.3251    0.3251

[169295 rows x 6 columns]