In [2]:
import pandas as pd
import json
import requests
from pprint import pprint
import alpaca_trade_api as tradeapi
from time import sleep

base_url = 'https://paper-api.alpaca.markets'
api_key = 'PK31BC6XPUTS7CVHNJQ3'
secret_key = 'reFlvUBcJJ0U9i6iVJJDLtI3P55YGavixpjGvPny'
api = tradeapi.REST(api_key, secret_key,base_url)
df = pd.read_csv('./sp500list1.csv')
bdf = pd.DataFrame(df)
bdf

    Symbol             Security             GICS Sector
0      MMM           3M Company             Industrials
1      ABT  Abbott Laboratories             Health Care
2     ABBV          AbbVie Inc.             Health Care
3     ABMD              Abiomed             Health Care
4      ACN            Accenture  Information Technology
..     ...                  ...                     ...
500    YUM      Yum! Brands Inc  Consumer Discretionary
501   ZBRA   Zebra Technologies  Information Technology
502    ZBH        Zimmer Biomet             Health Care
503   ZION        Zions Bancorp              Financials
504    ZTS               Zoetis             Health Care

[505 rows x 3 columns]

In [4]:
tckr = bdf['Symbol'].tolist()

In [5]:
price_info= []
count = 0
d = 0
for i in tckr:
#     try:
    barset = api.get_barset(f'{i}', 'day', limit=90)
    d=0
#         pprint(barset)
#         break
    for f in range(len(barset[i])):
            try:

                tckr_infoopening = barset[i][d].o
                tckr_infoClosing = barset[i][d].c
                tckr_infoHigh = barset[i][d].h
                tckr_infoLow = barset[i][d].l 
                d+=1
                day = d
                tckr_infoNHigh = barset[i][d].h


                info = {'Ticker':f'{i}',
                        'opening':tckr_infoopening,
                        'closing':tckr_infoClosing,
                        'NextHigh':tckr_infoNHigh,
                        'high':tckr_infoHigh,
                        'low':tckr_infoLow,
                       'day':day}
                price_info.append(info)
            except:
                pass

    pprint(i)
#         break
    count+=1
#     except:
#         count+=1
        
#         print(f'result error{i}')
#         pass

'MMM'
'ABT'
'ABBV'
'ABMD'
'ACN'
'ATVI'
'ADBE'
'AMD'
'AAP'
'AES'
'AFL'
'A'
'APD'
'AKAM'
'ALK'
'ALB'
'ARE'
'ALXN'
'ALGN'
'ALLE'
'LNT'
'ALL'
'GOOGL'
'GOOG'
'MO'
'AMZN'
'AMCR'
'AEE'
'AAL'
'AEP'
'AXP'
'AIG'
'AMT'
'AWK'
'AMP'
'ABC'
'AME'
'AMGN'
'APH'
'ADI'
'ANSS'
'ANTM'
'AON'
'AOS'
'APA'
'AAPL'
'AMAT'
'APTV'
'ADM'
'ANET'
'AJG'
'AIZ'
'T'
'ATO'
'ADSK'
'ADP'
'AZO'
'AVB'
'AVY'
'BKR'
'BLL'
'BAC'
'BK'
'BAX'
'BDX'
'BRK.B'
'BBY'
'BIO'
'BIIB'
'BLK'
'BA'
'BKNG'
'BWA'
'BXP'
'BSX'
'BMY'
'AVGO'
'BR'
'BF.B'
'CHRW'
'COG'
'CDNS'
'CZR'
'CPB'
'COF'
'CAH'
'KMX'
'CCL'
'CARR'
'CTLT'
'CAT'
'CBOE'
'CBRE'
'CDW'
'CE'
'CNC'
'CNP'
'CERN'
'CF'
'CRL'
'SCHW'
'CHTR'
'CVX'
'CMG'
'CB'
'CHD'
'CI'
'CINF'
'CTAS'
'CSCO'
'C'
'CFG'
'CTXS'
'CLX'
'CME'
'CMS'
'KO'
'CTSH'
'CL'
'CMCSA'
'CMA'
'CAG'
'COP'
'ED'
'STZ'
'COO'
'CPRT'
'GLW'
'CTVA'
'COST'
'CCI'
'CSX'
'CMI'
'CVS'
'DHI'
'DHR'
'DRI'
'DVA'
'DE'
'DAL'
'XRAY'
'DVN'
'DXCM'
'FANG'
'DLR'
'DFS'
'DISCA'
'DISCK'
'DISH'
'DG'
'DLTR'
'D'
'DPZ'
'DOV'
'DOW'
'DTE'
'DUK'
'DRE'
'DD'
'DXC'
'EMN'
'ETN'
'EBAY'
'ECL'
'EIX'
'EW'
'EA'
'EMR'
'ENPH'
'ETR'
'EOG'
'EFX'
'EQIX'
'EQR'
'ESS'
'EL'
'ETSY'
'EVRG'
'ES'
'RE'
'EXC'
'EXPE'
'EXPD'
'EXR'
'XOM'
'FFIV'
'FB'
'FAST'
'FRT'
'FDX'
'FIS'
'FITB'
'FE'
'FRC'
'FISV'
'FLT'
'FMC'
'F'
'FTNT'
'FTV'
'FBHS'
'FOXA'
'FOX'
'BEN'
'FCX'
'GPS'
'GRMN'
'IT'
'GNRC'
'GD'
'GE'
'GIS'
'GM'
'GPC'
'GILD'
'GL'
'GPN'
'GS'
'GWW'
'HAL'
'HBI'
'HIG'
'HAS'
'HCA'
'PEAK'
'HSIC'
'HSY'
'HES'
'HPE'
'HLT'
'HFC'
'HOLX'
'HD'
'HON'
'HRL'
'HST'
'HWM'
'HPQ'
'HUM'
'HBAN'
'HII'
'IEX'
'IDXX'
'INFO'
'ITW'
'ILMN'
'INCY'
'IR'
'INTC'
'ICE'
'IBM'
'IP'
'IPG'
'IFF'
'INTU'
'ISRG'
'IVZ'
'IPGP'
'IQV'
'IRM'
'JKHY'
'J'
'JBHT'
'SJM'
'JNJ'
'JCI'
'JPM'
'JNPR'
'KSU'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'K'
'KEY'
'KEYS'
'KMB'
'KIM'
'KMI'
'KLAC'
'KHC'
'KR'
'LB'
'LHX'
'LH'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'LRCX'
'LW'
'LVS'
'LEG'
'LDOS'
'LEN'
'LLY'
'LNC'
'LIN'
'LYV'
'LKQ'
'LMT'
'L'
'LOW'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'LUMN'
'LYB'
'MTB'
'MRO'
'MPC'
'MKTX'
'MAR'
'MMC'
'MLM'
'MAS'
'MA'
'MKC'
'MXIM'
'MCD'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'MCK'
'MDT'
'MRK'
'MET'
'MTD'
'MGM'
'MCHP'
'MU'
'MSFT'
'MAA'
'MHK'
'TAP'
'MDLZ'
'MPWR'
'MNST'
'MCO'
'MS'
'MOS'
'MSI'
'MSCI'
'NDAQ'
'NTAP'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'NFLX'
'NWL'
'NEM'
'NWSA'
'NWS'
'NEE'
'NLSN'
'NKE'
'NI'
'NSC'
'NTRS'
'NOC'
'NLOK'
'NCLH'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'NOV'
'NRG'
'NUE'
'NVDA'
'NVR'
'NXPI'
'ORLY'
'OXY'
'ODFL'
'OMC'
'OKE'
'ORCL'
'OTIS'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'PCAR'
'PKG'
'PH'
'PAYX'
'PAYC'
'PYPL'
'PENN'
'PNR'
'PBCT'
'PEP'
'PKI'
'PRGO'
'PFE'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'PM'
'PSX'
'PNW'
'PXD'
'PNC'
'POOL'
'PPG'
'PPL'
'PFG'
'PG'
'PGR'
'PLD'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'PRU'
'PTC'
'PEG'
'PSA'
'PHM'
'PVH'
'QRVO'
'PWR'
'QCOM'
'DGX'
'RL'
'RJF'
'RTX'
'O'
'REG'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'REGN'
'RF'
'RSG'
'RMD'
'RHI'
'ROK'
'ROL'
'ROP'
'ROST'
'RCL'
'SPGI'
'CRM'
'SBAC'
'SLB'
'STX'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'SEE'
'SRE'
'NOW'
'SHW'
'SPG'
'SWKS'
'SNA'
'SO'
'LUV'
'SWK'
'SBUX'
'STT'
'STE'
'SYK'
'SIVB'
'SYF'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'SNPS'
'SYY'
'TMUS'
'TROW'
'TTWO'
'TPR'
'TGT'
'TEL'
'TDY'
'TFX'
'TER'
'TSLA'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'TXN'
'TXT'
'TMO'
'TJX'
'TSCO'
'TT'
'TDG'
'TRV'
'TRMB'
'TFC'
'TWTR'
'TYL'
'TSN'
'UDR'
'ULTA'
'USB'
'UAA'
'UA'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'UNP'
'UAL'
'UNH'
'UPS'
'URI'
'UHS'
'UNM'
'VLO'
'VTR'
'VRSN'
'VRSK'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'VZ'
'VRTX'
'VFC'
'VIAC'
'VTRS'
'V'
'VNO'
'VMC'
'WRB'
'WAB'
'WMT'
'WBA'
'DIS'
'WM'
'WAT'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'WEC'
'WFC'
'WELL'
'WST'
'WDC'
'WU'
'WRK'
'WY'
'WHR'
'WMB'
'WLTW'
'WYNN'
'XEL'

sleep 3 seconds and retrying https://data.alpaca.markets/v1/bars/day 3 more time(s)...

'XLNX'
'XYL'
'YUM'
'ZBRA'
'ZBH'
'ZION'
'ZTS'

In [6]:
df = pd.DataFrame(price_info)
df

      Ticker  opening  closing  NextHigh      high       low  day
0        MMM   202.29   201.37  201.8600  203.5900  200.4200    1
1        MMM   201.99   200.62  200.9900  201.8600  199.5300    2
2        MMM   200.57   196.90  197.5000  200.9900  196.8102    3
3        MMM   196.80   195.15  193.5700  197.5000  193.0000    4
4        MMM   193.04   191.54  196.6255  193.5700  191.5300    5
...      ...      ...      ...       ...       ...       ...  ...
44940    ZTS   198.89   197.16  198.9500  199.3699  195.7700   85
44941    ZTS   196.97   197.46  201.7700  198.9500  195.7900   86
44942    ZTS   198.82   200.38  202.8000  201.7700  198.8200   87
44943    ZTS   201.13   202.26  202.9300  202.8000  200.1200   88
44944    ZTS   202.42   202.70  206.1700  202.9300  200.7600   89

[44945 rows x 7 columns]

In [7]:
df.to_csv(r'../Machine_learning/MA500Data.csv', index = False)